// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using The_Bread_Pit.Models;

#nullable disable

namespace The_Bread_Pit.Migrations
{
    [DbContext(typeof(TheBreadPitContext))]
    [Migration("20240215211139_AddWinkelmandjeItem")]
    partial class AddWinkelmandjeItem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("The_Bread_Pit.Models.Categorie", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryID"));

                    b.Property<string>("CategorieNaam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryID");

                    b.ToTable("Categorien");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            CategorieNaam = "Soep"
                        },
                        new
                        {
                            CategoryID = 2,
                            CategorieNaam = "Salades"
                        },
                        new
                        {
                            CategoryID = 3,
                            CategorieNaam = "Pasta"
                        },
                        new
                        {
                            CategoryID = 4,
                            CategorieNaam = "Snack"
                        },
                        new
                        {
                            CategoryID = 5,
                            CategorieNaam = "Belegde broodjes"
                        },
                        new
                        {
                            CategoryID = 6,
                            CategorieNaam = "Zoet / Fruit"
                        },
                        new
                        {
                            CategoryID = 7,
                            CategorieNaam = "Andere"
                        },
                        new
                        {
                            CategoryID = 8,
                            CategorieNaam = "Dranken"
                        });
                });

            modelBuilder.Entity("The_Bread_Pit.Models.Produkt", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductID"));

                    b.Property<int?>("CategorieCategoryID")
                        .HasColumnType("int");

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<string>("Omschrijving")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Prijs")
                        .HasColumnType("decimal(20,2)");

                    b.Property<string>("ProduktNaam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductID");

                    b.HasIndex("CategorieCategoryID");

                    b.ToTable("Produkten");

                    b.HasData(
                        new
                        {
                            ProductID = 1,
                            CategoryID = 1,
                            Omschrijving = "Soep van de dag",
                            Prijs = 1.1m,
                            ProduktNaam = "Soep"
                        },
                        new
                        {
                            ProductID = 2,
                            CategoryID = 1,
                            Omschrijving = "Stuk stokbrood",
                            Prijs = 0.55m,
                            ProduktNaam = "Stokbrood"
                        },
                        new
                        {
                            ProductID = 3,
                            CategoryID = 1,
                            Omschrijving = "Blokje melkerij boter",
                            Prijs = 0.55m,
                            ProduktNaam = "Boter"
                        },
                        new
                        {
                            ProductID = 4,
                            CategoryID = 1,
                            Omschrijving = "Sla met stukjes Kip",
                            Prijs = 5m,
                            ProduktNaam = "Ceasar Salad"
                        },
                        new
                        {
                            ProductID = 5,
                            CategoryID = 1,
                            Omschrijving = "Pasta Klein",
                            Prijs = 5.5m,
                            ProduktNaam = "Pasta 4 Kazen"
                        });
                });

            modelBuilder.Entity("The_Bread_Pit.Models.WinkelmandjeItem", b =>
                {
                    b.Property<int>("WinkelmandjeItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WinkelmandjeItemID"));

                    b.Property<int>("Aantal")
                        .HasColumnType("int");

                    b.Property<int>("ProduktProductID")
                        .HasColumnType("int");

                    b.Property<string>("SessieId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WinkelmandjeItemID");

                    b.HasIndex("ProduktProductID");

                    b.ToTable("WinkelmandjeItems");
                });

            modelBuilder.Entity("The_Bread_Pit.Models.Produkt", b =>
                {
                    b.HasOne("The_Bread_Pit.Models.Categorie", "Categorie")
                        .WithMany()
                        .HasForeignKey("CategorieCategoryID");

                    b.Navigation("Categorie");
                });

            modelBuilder.Entity("The_Bread_Pit.Models.WinkelmandjeItem", b =>
                {
                    b.HasOne("The_Bread_Pit.Models.Produkt", "Produkt")
                        .WithMany()
                        .HasForeignKey("ProduktProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produkt");
                });
#pragma warning restore 612, 618
        }
    }
}
